call plug#begin()

Plug 'tpope/vim-sensible'

Plug 'itchyny/lightline.vim'

Plug 'python-mode/python-mode', { 'for': 'python', 'branch': 'develop' }

Plug 'elixir-lang/vim-elixir'

Plug 'slashmili/alchemist.vim'

Plug '/usr/local/opt/fzf'

Plug 'junegunn/fzf.vim'

call plug#end()

autocmd BufWritePre * :%s/\s\+$//e

let g:pymode_options_colorcolumn = 0
let g:pymode_folding = 0
let g:pymode_rope = 0

autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

set tabstop=4
set shiftwidth=4
set expandtab

set wildmode=longest,list,full
set wildmenu

let mapleader = " "
nmap <leader>o :GFiles<CR>
nmap <leader>O :Files<CR>
nmap <leader>b :Buffers<CR>
nmap <leader>h :History<CR>
nnoremap <leader>' ciw''<Esc>P
nnoremap <leader>" ciw""<Esc>P
nnoremap <leader>d daW"=substitute(@@,"'\\\|\"","","g")<CR>P
map <leader>g :YcmCompleter GoToDefinitionElseDeclaration<CR>
