call plug#begin()

Plug 'tpope/vim-sensible'

Plug 'itchyny/lightline.vim'

Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }

Plug 'junegunn/fzf.vim'

call plug#end()

autocmd BufWritePre * :%s/\s\+$//e

set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4
set autoindent
set encoding=utf-8
set fileformat=unix

let python_highlight_all=1
syntax on

set wildmode=longest,list,full
set wildmenu

let mapleader = " "
nmap <leader>o :GFiles<CR>
nmap <leader>O :Files<CR>
nmap <leader>b :Buffers<CR>
nmap <leader>h :History<CR>
nnoremap <leader>' ciw''<Esc>P
nnoremap <leader>" ciw""<Esc>P
nnoremap <leader>d daW"=substitute(@@,"'\\\|\"","","g")<CR>P
map <leader>g :YcmCompleter GoToDefinitionElseDeclaration<CR>
